### Cadastrar uma forma de pagamento
POST https://localhost:5001/api/categoria/create
Content-Type: application/json

{
    "Nome" : "Bebida"
}

### Listar todas as formas de pagamento
GET https://localhost:5001/api/formapagamento/list