### Cadastrar uma forma de pagamento
POST https://localhost:5001/api/formapagamento/create
Content-Type: application/json

{
    "MetodoPagamento" : "Cartão",
    "OpcaoPagamento": "Parcelado"
}

### Listar todas as formas de pagamento
GET https://localhost:5001/api/formapagamento/list